name: Continuous Deployment

on:
  push:
    branches: [ "dev" ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: false
        
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Compare branch 코드 내려 받기
      - name: Checkout PR
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      # 2. 자바 환경 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Docker 이미지 build 및 push
      - name: docker build and push
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/momo-was .
          docker push ${{ secrets.DOCKER_USERNAME }}/momo-was

      # 4. ec2 pull
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.KEY }}
          script: |
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            docker rm -f momo-app || true
            sudo lsof -i :8080 | grep LISTEN | awk '{print $2}' | xargs -r sudo kill -9
            docker rmi ${{ secrets.DOCKER_USERNAME }}/momo-was || true
            docker pull ${{ secrets.DOCKER_USERNAME }}/momo-was
            docker run --env-file /home/ubuntu/momo-was/.env \
              -d --name momo-app -p 8080:8080 \
              ${{ secrets.DOCKER_USERNAME }}/momo-was
