name: Continuous Integration

on:
  pull_request:
    branches: [ "dev" ]

permissions:
  contents: read

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      # 1. Compare branch 코드 내려받기
      - name: Checkout PR
        uses: actions/checkout@v3

      # 2. Debug Info (환경 변수 값 출력)
      - name: Print environment variables
        env:
          COOLSMS_API_KEY: ${{ secrets.COOLSMS_API_KEY }}
          COOLSMS_FROM_NUMBER: ${{ secrets.COOLSMS_FROM_NUMBER }}
          COOLSMS_SECRET_KEY: ${{ secrets.COOLSMS_SECRET_KEY }}
          DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
          DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
          DATABASE_USER: ${{ secrets.DATABASE_USER }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          GOOGLE_REDIRECT_URI: ${{ secrets.GOOGLE_REDIRECT_URI }}
          JWT_ACCESS_EXPIRATION: ${{ secrets.JWT_ACCESS_EXPIRATION }}
          JWT_ISSUER: ${{ secrets.JWT_ISSUER }}
          JWT_REFRESH_EXPIRATION: ${{ secrets.JWT_REFRESH_EXPIRATION }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          NAVER_CLIENT_ID: ${{ secrets.NAVER_CLIENT_ID }}
          NAVER_CLIENT_SECRET: ${{ secrets.NAVER_CLIENT_SECRET }}
          NAVER_REDIRECT_URI: ${{ secrets.NAVER_REDIRECT_URI }}
        run: |
          echo "COOLSMS_API_KEY=$COOLSMS_API_KEY"
          echo "COOLSMS_FROM_NUMBER=$COOLSMS_FROM_NUMBER"
          echo "COOLSMS_SECRET_KEY=$COOLSMS_SECRET_KEY"
          echo "DATABASE_HOST=$DATABASE_HOST"
          echo "DATABASE_NAME=$DATABASE_NAME"
          echo "DATABASE_PASSWORD=$DATABASE_PASSWORD"
          echo "DATABASE_PORT=$DATABASE_PORT"
          echo "DATABASE_USER=$DATABASE_USER"
          echo "GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID"
          echo "GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET"
          echo "GOOGLE_REDIRECT_URI=$GOOGLE_REDIRECT_URI"
          echo "JWT_ACCESS_EXPIRATION=$JWT_ACCESS_EXPIRATION"
          echo "JWT_ISSUER=$JWT_ISSUER"
          echo "JWT_REFRESH_EXPIRATION=$JWT_REFRESH_EXPIRATION"
          echo "JWT_SECRET=$JWT_SECRET"
          echo "NAVER_CLIENT_ID=$NAVER_CLIENT_ID"
          echo "NAVER_CLIENT_SECRET=$NAVER_CLIENT_SECRET"
          echo "NAVER_REDIRECT_URI=$NAVER_REDIRECT_URI"

      # 3. 자바 환경 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 4. Gradle build 실행
      - name: Build with Gradle
        env:
          COOLSMS_API_KEY: ${{ secrets.COOLSMS_API_KEY }}
          COOLSMS_FROM_NUMBER: ${{ secrets.COOLSMS_FROM_NUMBER }}
          COOLSMS_SECRET_KEY: ${{ secrets.COOLSMS_SECRET_KEY }}
          DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
          DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
          DATABASE_USER: ${{ secrets.DATABASE_USER }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          GOOGLE_REDIRECT_URI: ${{ secrets.GOOGLE_REDIRECT_URI }}
          JWT_ACCESS_EXPIRATION: ${{ secrets.JWT_ACCESS_EXPIRATION }}
          JWT_ISSUER: ${{ secrets.JWT_ISSUER }}
          JWT_REFRESH_EXPIRATION: ${{ secrets.JWT_REFRESH_EXPIRATION }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          NAVER_CLIENT_ID: ${{ secrets.NAVER_CLIENT_ID }}
          NAVER_CLIENT_SECRET: ${{ secrets.NAVER_CLIENT_SECRET }}
          NAVER_REDIRECT_URI: ${{ secrets.NAVER_REDIRECT_URI }}
        run: |
          chmod +x ./gradlew
          ./gradlew build
